# Generated by Django 5.0.2 on 2024-03-03 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='oblate_method',
            new_name='payment_method',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='paid_lesson',
        ),
    ]
