# Generated by Django 5.0.2 on 2024-03-04 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_oblate_method_payment_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Payment date'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.IntegerField(choices=[(1, 'Cash'), (2, 'Transfer'), (3, 'Acquiring')], default=3, verbose_name='Payment method'),
        ),
    ]
