# Generated by Django 5.0.2 on 2024-03-03 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_course_price_alter_lesson_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='price',
        ),
        migrations.AddField(
            model_name='course',
            name='price_rub',
            field=models.IntegerField(default=0, verbose_name='Course price (RUB)'),
        ),
    ]
